project_id = "yfaiauooxwvekdimfeuu"

[auth.email.template.confirmation]
subject = "Confirm your DIL signup"
content_path = "supabase/email-templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your DIL password"
content_path = "supabase/email-templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your DIL LMS magic link"
content_path = "supabase/email-templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirm your DIL email change"
content_path = "supabase/email-templates/change-email.html"

[auth.email.template.invite]
subject = "You've been invited to DIL"
content_path = "supabase/email-templates/invite-user.html"

[auth.email.template.reauthentication]
subject = "Confirm reauthentication"
content_path = "supabase/email-templates/reauthentication.html"
[functions.reset-password]
enabled = true
verify_jwt = true
import_map = "./functions/reset-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-password/*.html" ]

[functions.invite-user]
enabled = true
verify_jwt = true
import_map = "./functions/invite-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/invite-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/invite-user/*.html" ]

[functions.get-users]
enabled = true
verify_jwt = true
import_map = "./functions/get-users/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-users/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-users/*.html" ]

[functions.delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-user/*.html" ]

[functions.reset-user-password]
enabled = true
verify_jwt = true
import_map = "./functions/reset-user-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-user-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-user-password/*.html" ]

[functions.update-user]
enabled = true
verify_jwt = true
import_map = "./functions/update-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-user/*.html" ]

[functions.update-unconfirmed-user]
verify_jwt = true
import_map = "./functions/update-unconfirmed-user/deno.json"
entrypoint = "./functions/update-unconfirmed-user/index.ts"
