-- Consolidated Refactor Script (v2 - Idempotent)
-- This script removes old course structures and creates the new ones.
-- It is safe to run multiple times.

-- 1. CLEANUP: Drop all old and potentially partially-created structures first.

DROP TABLE IF EXISTS public.user_course_progress CASCADE;
DROP TABLE IF EXISTS public.user_content_item_progress CASCADE;
DROP TABLE IF EXISTS public.question_options CASCADE;
DROP TABLE IF EXISTS public.quiz_questions CASCADE;
DROP TABLE IF EXISTS public.course_lesson_content CASCADE;

-- Remove old content-related columns from the course_lessons table
ALTER TABLE public.course_lessons DROP COLUMN IF EXISTS type CASCADE;
ALTER TABLE public.course_lessons DROP COLUMN IF EXISTS content CASCADE;
ALTER TABLE public.course_lessons DROP COLUMN IF EXISTS duration CASCADE;


-- 2. SETUP: Create the new 3-tier structure.

-- Create the table for lesson content items.
CREATE TABLE IF NOT EXISTS public.course_lesson_content (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    lesson_id uuid NOT NULL REFERENCES public.course_lessons(id) ON DELETE CASCADE,
    title text,
    content_type text NOT NULL,
    content_path text,
    position integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.course_lesson_content IS 'Stores individual content items (video, quiz, etc.) for a lesson.';
ALTER TABLE public.course_lesson_content ENABLE ROW LEVEL SECURITY;

-- Create the normalized tables for quizzes.
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    lesson_content_id uuid NOT NULL REFERENCES public.course_lesson_content(id) ON DELETE CASCADE,
    question_text text NOT NULL,
    position integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.quiz_questions IS 'Stores the questions for a specific lesson quiz content item.';
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.question_options (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    question_id uuid NOT NULL REFERENCES public.quiz_questions(id) ON DELETE CASCADE,
    option_text text NOT NULL,
    is_correct boolean DEFAULT false NOT NULL,
    position integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.question_options IS 'Stores the answer options for a quiz question.';
ALTER TABLE public.question_options ENABLE ROW LEVEL SECURITY;

-- Create the new table for tracking user progress at the content item level.
CREATE TABLE IF NOT EXISTS public.user_content_item_progress (
    id bigint PRIMARY KEY generated by default as identity,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id uuid NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
    lesson_id uuid NOT NULL REFERENCES public.course_lessons(id) ON DELETE CASCADE,
    lesson_content_id uuid NOT NULL REFERENCES public.course_lesson_content(id) ON DELETE CASCADE,
    status text DEFAULT 'not_started' NOT NULL, -- e.g., 'not_started', 'in_progress', 'completed'
    progress_data jsonb, -- For video: {"seconds": 120}, For quiz: {"submission_id": "uuid"}
    completed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
COMMENT ON TABLE public.user_content_item_progress IS 'Tracks completion status for each content item within a lesson for a user.';
ALTER TABLE public.user_content_item_progress ENABLE ROW LEVEL SECURITY;


-- 3. ALTER: Add the new foreign key to quiz_submissions.
ALTER TABLE public.quiz_submissions
ADD COLUMN IF NOT EXISTS lesson_content_id uuid REFERENCES public.course_lesson_content(id) ON DELETE SET NULL;

-- 4. ADD DURATION to lessons table
alter table public.course_lessons
add column if not exists duration_text text;
comment on column public.course_lessons.duration_text is 'Estimated time to complete the entire lesson container.';
