-- Migration: Add Sample Security Data for Testing Pagination
-- Description: Inserts many sample security alerts and access logs to test scroll pagination
-- Date: 2024-01-15

-- Clear existing sample data first
DELETE FROM security_alerts WHERE message IN (
  'Multiple failed login attempts detected',
  'System backup completed successfully'
);

DELETE FROM access_logs WHERE user_email IN (
  'admin@dil.com',
  'teacher@dil.com', 
  'unknown@dil.com'
);

-- Insert 50 sample security alerts
INSERT INTO security_alerts (alert_type, message, severity, created_at) VALUES
  ('warning', 'Multiple failed login attempts detected from IP 192.168.1.50', 'medium', NOW() - INTERVAL '1 minute'),
  ('info', 'System backup completed successfully', 'low', NOW() - INTERVAL '2 minutes'),
  ('error', 'Database connection timeout detected', 'high', NOW() - INTERVAL '3 minutes'),
  ('warning', 'Unusual login pattern detected for user john@dil.com', 'medium', NOW() - INTERVAL '4 minutes'),
  ('success', 'Security scan completed - no threats found', 'low', NOW() - INTERVAL '5 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 203.0.113.10', 'medium', NOW() - INTERVAL '6 minutes'),
  ('info', 'SSL certificate renewed successfully', 'low', NOW() - INTERVAL '7 minutes'),
  ('error', 'Disk space usage exceeded 90%', 'high', NOW() - INTERVAL '8 minutes'),
  ('warning', 'Suspicious activity detected in admin panel', 'medium', NOW() - INTERVAL '9 minutes'),
  ('info', 'Firewall rules updated successfully', 'low', NOW() - INTERVAL '10 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 10.0.0.15', 'medium', NOW() - INTERVAL '11 minutes'),
  ('error', 'Memory usage exceeded 85%', 'high', NOW() - INTERVAL '12 minutes'),
  ('info', 'Security patches applied successfully', 'low', NOW() - INTERVAL '13 minutes'),
  ('warning', 'Unusual file access pattern detected', 'medium', NOW() - INTERVAL '14 minutes'),
  ('success', 'Vulnerability scan completed - 2 minor issues found', 'low', NOW() - INTERVAL '15 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 172.16.0.25', 'medium', NOW() - INTERVAL '16 minutes'),
  ('info', 'Database backup verification completed', 'low', NOW() - INTERVAL '17 minutes'),
  ('error', 'Network latency exceeded threshold', 'high', NOW() - INTERVAL '18 minutes'),
  ('warning', 'Suspicious email activity detected', 'medium', NOW() - INTERVAL '19 minutes'),
  ('info', 'User session cleanup completed', 'low', NOW() - INTERVAL '20 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 198.51.100.30', 'medium', NOW() - INTERVAL '21 minutes'),
  ('error', 'API rate limit exceeded', 'high', NOW() - INTERVAL '22 minutes'),
  ('info', 'Security log rotation completed', 'low', NOW() - INTERVAL '23 minutes'),
  ('warning', 'Unusual database query pattern detected', 'medium', NOW() - INTERVAL '24 minutes'),
  ('success', 'Malware scan completed - clean', 'low', NOW() - INTERVAL '25 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 192.0.2.40', 'medium', NOW() - INTERVAL '26 minutes'),
  ('info', 'SSL certificate validation completed', 'low', NOW() - INTERVAL '27 minutes'),
  ('error', 'CPU usage exceeded 90%', 'high', NOW() - INTERVAL '28 minutes'),
  ('warning', 'Suspicious network traffic detected', 'medium', NOW() - INTERVAL '29 minutes'),
  ('info', 'Security policy update completed', 'low', NOW() - INTERVAL '30 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 203.0.113.50', 'medium', NOW() - INTERVAL '31 minutes'),
  ('error', 'Database connection pool exhausted', 'high', NOW() - INTERVAL '32 minutes'),
  ('info', 'Backup integrity check completed', 'low', NOW() - INTERVAL '33 minutes'),
  ('warning', 'Unusual API usage pattern detected', 'medium', NOW() - INTERVAL '34 minutes'),
  ('success', 'Security audit completed - compliant', 'low', NOW() - INTERVAL '35 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 10.0.0.35', 'medium', NOW() - INTERVAL '36 minutes'),
  ('info', 'Firewall log analysis completed', 'low', NOW() - INTERVAL '37 minutes'),
  ('error', 'Disk I/O performance degraded', 'high', NOW() - INTERVAL '38 minutes'),
  ('warning', 'Suspicious user behavior detected', 'medium', NOW() - INTERVAL '39 minutes'),
  ('info', 'Security monitoring system updated', 'low', NOW() - INTERVAL '40 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 172.16.0.45', 'medium', NOW() - INTERVAL '41 minutes'),
  ('error', 'Memory leak detected in application', 'high', NOW() - INTERVAL '42 minutes'),
  ('info', 'SSL certificate expiration check completed', 'low', NOW() - INTERVAL '43 minutes'),
  ('warning', 'Unusual system call pattern detected', 'medium', NOW() - INTERVAL '44 minutes'),
  ('success', 'Security training completion rate: 95%', 'low', NOW() - INTERVAL '45 minutes'),
  ('warning', 'Multiple failed login attempts detected from IP 198.51.100.55', 'medium', NOW() - INTERVAL '46 minutes'),
  ('info', 'Database performance optimization completed', 'low', NOW() - INTERVAL '47 minutes'),
  ('error', 'Network bandwidth usage exceeded limit', 'high', NOW() - INTERVAL '48 minutes'),
  ('warning', 'Suspicious file upload activity detected', 'medium', NOW() - INTERVAL '49 minutes'),
  ('info', 'Security incident response drill completed', 'low', NOW() - INTERVAL '50 minutes');

-- Insert 100 sample access logs
INSERT INTO access_logs (user_email, action, ip_address, location, status, created_at) VALUES
  ('admin@dil.com', 'Login', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '1 minute'),
  ('teacher@dil.com', 'Course Update', '192.168.1.101', 'London, UK', 'success', NOW() - INTERVAL '2 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.45', 'Unknown', 'failed', NOW() - INTERVAL '3 minutes'),
  ('student1@dil.com', 'Course Access', '192.168.1.102', 'Toronto, CA', 'success', NOW() - INTERVAL '4 minutes'),
  ('admin@dil.com', 'User Management', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '5 minutes'),
  ('teacher2@dil.com', 'Assignment Creation', '192.168.1.103', 'Berlin, DE', 'success', NOW() - INTERVAL '6 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.46', 'Unknown', 'failed', NOW() - INTERVAL '7 minutes'),
  ('student2@dil.com', 'Quiz Submission', '192.168.1.104', 'Sydney, AU', 'success', NOW() - INTERVAL '8 minutes'),
  ('admin@dil.com', 'System Settings', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '9 minutes'),
  ('teacher3@dil.com', 'Grade Update', '192.168.1.105', 'Paris, FR', 'success', NOW() - INTERVAL '10 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.47', 'Unknown', 'failed', NOW() - INTERVAL '11 minutes'),
  ('student3@dil.com', 'Discussion Post', '192.168.1.106', 'Tokyo, JP', 'success', NOW() - INTERVAL '12 minutes'),
  ('admin@dil.com', 'Security Audit', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '13 minutes'),
  ('teacher4@dil.com', 'Course Enrollment', '192.168.1.107', 'Madrid, ES', 'success', NOW() - INTERVAL '14 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.48', 'Unknown', 'failed', NOW() - INTERVAL '15 minutes'),
  ('student4@dil.com', 'File Upload', '192.168.1.108', 'Mumbai, IN', 'success', NOW() - INTERVAL '16 minutes'),
  ('admin@dil.com', 'Database Backup', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '17 minutes'),
  ('teacher5@dil.com', 'Student Assessment', '192.168.1.109', 'Rome, IT', 'success', NOW() - INTERVAL '18 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.49', 'Unknown', 'failed', NOW() - INTERVAL '19 minutes'),
  ('student5@dil.com', 'Course Completion', '192.168.1.110', 'São Paulo, BR', 'success', NOW() - INTERVAL '20 minutes'),
  ('admin@dil.com', 'System Maintenance', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '21 minutes'),
  ('teacher6@dil.com', 'Resource Creation', '192.168.1.111', 'Amsterdam, NL', 'success', NOW() - INTERVAL '22 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.50', 'Unknown', 'failed', NOW() - INTERVAL '23 minutes'),
  ('student6@dil.com', 'Peer Review', '192.168.1.112', 'Seoul, KR', 'success', NOW() - INTERVAL '24 minutes'),
  ('admin@dil.com', 'User Permissions', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '25 minutes'),
  ('teacher7@dil.com', 'Course Analytics', '192.168.1.113', 'Stockholm, SE', 'success', NOW() - INTERVAL '26 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.51', 'Unknown', 'failed', NOW() - INTERVAL '27 minutes'),
  ('student7@dil.com', 'Assignment Download', '192.168.1.114', 'Mexico City, MX', 'success', NOW() - INTERVAL '28 minutes'),
  ('admin@dil.com', 'System Logs', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '29 minutes'),
  ('teacher8@dil.com', 'Student Feedback', '192.168.1.115', 'Vienna, AT', 'success', NOW() - INTERVAL '30 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.52', 'Unknown', 'failed', NOW() - INTERVAL '31 minutes'),
  ('student8@dil.com', 'Course Registration', '192.168.1.116', 'Cairo, EG', 'success', NOW() - INTERVAL '32 minutes'),
  ('admin@dil.com', 'Security Settings', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '33 minutes'),
  ('teacher9@dil.com', 'Content Management', '192.168.1.117', 'Dublin, IE', 'success', NOW() - INTERVAL '34 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.53', 'Unknown', 'failed', NOW() - INTERVAL '35 minutes'),
  ('student9@dil.com', 'Discussion Reply', '192.168.1.118', 'Bangkok, TH', 'success', NOW() - INTERVAL '36 minutes'),
  ('admin@dil.com', 'System Update', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '37 minutes'),
  ('teacher10@dil.com', 'Student Progress', '192.168.1.119', 'Warsaw, PL', 'success', NOW() - INTERVAL '38 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.54', 'Unknown', 'failed', NOW() - INTERVAL '39 minutes'),
  ('student10@dil.com', 'Certificate Download', '192.168.1.120', 'Lagos, NG', 'success', NOW() - INTERVAL '40 minutes'),
  ('admin@dil.com', 'User Reports', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '41 minutes'),
  ('teacher11@dil.com', 'Course Syllabus', '192.168.1.121', 'Prague, CZ', 'success', NOW() - INTERVAL '42 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.55', 'Unknown', 'failed', NOW() - INTERVAL '43 minutes'),
  ('student11@dil.com', 'Quiz Attempt', '192.168.1.122', 'Helsinki, FI', 'success', NOW() - INTERVAL '44 minutes'),
  ('admin@dil.com', 'System Monitoring', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '45 minutes'),
  ('teacher12@dil.com', 'Student Communication', '192.168.1.123', 'Budapest, HU', 'success', NOW() - INTERVAL '46 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.56', 'Unknown', 'failed', NOW() - INTERVAL '47 minutes'),
  ('student12@dil.com', 'Course Materials', '192.168.1.124', 'Athens, GR', 'success', NOW() - INTERVAL '48 minutes'),
  ('admin@dil.com', 'Database Query', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '49 minutes'),
  ('teacher13@dil.com', 'Assessment Review', '192.168.1.125', 'Lisbon, PT', 'success', NOW() - INTERVAL '50 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.57', 'Unknown', 'failed', NOW() - INTERVAL '51 minutes'),
  ('student13@dil.com', 'Peer Assessment', '192.168.1.126', 'Bucharest, RO', 'success', NOW() - INTERVAL '52 minutes'),
  ('admin@dil.com', 'System Configuration', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '53 minutes'),
  ('teacher14@dil.com', 'Student Records', '192.168.1.127', 'Sofia, BG', 'success', NOW() - INTERVAL '54 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.58', 'Unknown', 'failed', NOW() - INTERVAL '55 minutes'),
  ('student14@dil.com', 'Course Evaluation', '192.168.1.128', 'Zagreb, HR', 'success', NOW() - INTERVAL '56 minutes'),
  ('admin@dil.com', 'System Diagnostics', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '57 minutes'),
  ('teacher15@dil.com', 'Content Review', '192.168.1.129', 'Ljubljana, SI', 'success', NOW() - INTERVAL '58 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.59', 'Unknown', 'failed', NOW() - INTERVAL '59 minutes'),
  ('student15@dil.com', 'Assignment Review', '192.168.1.130', 'Tallinn, EE', 'success', NOW() - INTERVAL '60 minutes'),
  ('admin@dil.com', 'System Backup', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '61 minutes'),
  ('teacher16@dil.com', 'Student Support', '192.168.1.131', 'Riga, LV', 'success', NOW() - INTERVAL '62 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.60', 'Unknown', 'failed', NOW() - INTERVAL '63 minutes'),
  ('student16@dil.com', 'Course Feedback', '192.168.1.132', 'Vilnius, LT', 'success', NOW() - INTERVAL '64 minutes'),
  ('admin@dil.com', 'System Recovery', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '65 minutes'),
  ('teacher17@dil.com', 'Assessment Design', '192.168.1.133', 'Bratislava, SK', 'success', NOW() - INTERVAL '66 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.61', 'Unknown', 'failed', NOW() - INTERVAL '67 minutes'),
  ('student17@dil.com', 'Course Planning', '192.168.1.134', 'Bratislava, SK', 'success', NOW() - INTERVAL '68 minutes'),
  ('admin@dil.com', 'System Optimization', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '69 minutes'),
  ('teacher18@dil.com', 'Student Mentoring', '192.168.1.135', 'Bratislava, SK', 'success', NOW() - INTERVAL '70 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.62', 'Unknown', 'failed', NOW() - INTERVAL '71 minutes'),
  ('student18@dil.com', 'Course Research', '192.168.1.136', 'Bratislava, SK', 'success', NOW() - INTERVAL '72 minutes'),
  ('admin@dil.com', 'System Validation', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '73 minutes'),
  ('teacher19@dil.com', 'Student Development', '192.168.1.137', 'Bratislava, SK', 'success', NOW() - INTERVAL '74 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.63', 'Unknown', 'failed', NOW() - INTERVAL '75 minutes'),
  ('student19@dil.com', 'Course Analysis', '192.168.1.138', 'Bratislava, SK', 'success', NOW() - INTERVAL '76 minutes'),
  ('admin@dil.com', 'System Verification', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '77 minutes'),
  ('teacher20@dil.com', 'Student Evaluation', '192.168.1.139', 'Bratislava, SK', 'success', NOW() - INTERVAL '78 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.64', 'Unknown', 'failed', NOW() - INTERVAL '79 minutes'),
  ('student20@dil.com', 'Course Synthesis', '192.168.1.140', 'Bratislava, SK', 'success', NOW() - INTERVAL '80 minutes'),
  ('admin@dil.com', 'System Testing', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '81 minutes'),
  ('teacher21@dil.com', 'Student Assessment', '192.168.1.141', 'Bratislava, SK', 'success', NOW() - INTERVAL '82 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.65', 'Unknown', 'failed', NOW() - INTERVAL '83 minutes'),
  ('student21@dil.com', 'Course Reflection', '192.168.1.142', 'Bratislava, SK', 'success', NOW() - INTERVAL '84 minutes'),
  ('admin@dil.com', 'System Deployment', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '85 minutes'),
  ('teacher22@dil.com', 'Student Guidance', '192.168.1.143', 'Bratislava, SK', 'success', NOW() - INTERVAL '86 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.66', 'Unknown', 'failed', NOW() - INTERVAL '87 minutes'),
  ('student22@dil.com', 'Course Integration', '192.168.1.144', 'Bratislava, SK', 'success', NOW() - INTERVAL '88 minutes'),
  ('admin@dil.com', 'System Integration', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '89 minutes'),
  ('teacher23@dil.com', 'Student Collaboration', '192.168.1.145', 'Bratislava, SK', 'success', NOW() - INTERVAL '90 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.67', 'Unknown', 'failed', NOW() - INTERVAL '91 minutes'),
  ('student23@dil.com', 'Course Innovation', '192.168.1.146', 'Bratislava, SK', 'success', NOW() - INTERVAL '92 minutes'),
  ('admin@dil.com', 'System Innovation', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '93 minutes'),
  ('teacher24@dil.com', 'Student Innovation', '192.168.1.147', 'Bratislava, SK', 'success', NOW() - INTERVAL '94 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.68', 'Unknown', 'failed', NOW() - INTERVAL '95 minutes'),
  ('student24@dil.com', 'Course Transformation', '192.168.1.148', 'Bratislava, SK', 'success', NOW() - INTERVAL '96 minutes'),
  ('admin@dil.com', 'System Transformation', '192.168.1.100', 'New York, US', 'success', NOW() - INTERVAL '97 minutes'),
  ('teacher25@dil.com', 'Student Transformation', '192.168.1.149', 'Bratislava, SK', 'success', NOW() - INTERVAL '98 minutes'),
  ('unknown@dil.com', 'Login Attempt', '203.0.113.69', 'Unknown', 'failed', NOW() - INTERVAL '99 minutes'),
  ('student25@dil.com', 'Course Evolution', '192.168.1.150', 'Bratislava, SK', 'success', NOW() - INTERVAL '100 minutes');
