// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { handleAuthError } from '@/utils/authErrorHandler';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://yfaiauooxwvekdimfeuu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYWlhdW9veHd2ZWtkaW1mZXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTEyMDksImV4cCI6MjA2NzE2NzIwOX0.rAc49wpyOERCcNpxpI12TPn6NSSoySToNq33bhakEho';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if environment variables are missing and show a warning
if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.warn('⚠️ Supabase environment variables are missing. Using fallback values. Please create a .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-react'
    }
  }
});

// Helper function to check user profile with retry
const checkUserProfileWithRetry = async (userId: string, maxRetries: number = 2): Promise<{ data: any; error: any }> => {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`Profile check attempt ${attempt}/${maxRetries} for user ${userId}`);
      
      const profileCheckPromise = supabase
        .from('profiles')
        .select('id')
        .eq('id', userId)
        .single();
      
      // Add timeout to prevent blocking - increased from 3s to 15s
      const timeoutPromise = new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Profile check timeout')), 15000)
      );
      
      const result = await Promise.race([
        profileCheckPromise,
        timeoutPromise
      ]) as any;
      
      return result;
    } catch (error) {
      console.warn(`Profile check attempt ${attempt} failed:`, error);
      
      if (attempt === maxRetries) {
        // Last attempt failed, return the error
        return { data: null, error };
      }
      
      // Wait before retry (exponential backoff)
      await new Promise(resolve => setTimeout(resolve, 1000 * attempt));
    }
  }
  
  return { data: null, error: new Error('All profile check attempts failed') };
};

// Global error interceptor for handling user_not_found errors
supabase.auth.onAuthStateChange(async (event, session) => {
  if (event === 'TOKEN_REFRESHED' && session) {
    try {
      // Check if the user still exists in the database with retry
      const { data: profile, error } = await checkUserProfileWithRetry(session.user.id);
      
      if (error && error.code === 'PGRST116') {
        // User not found in database, sign them out
        console.warn('User not found in database, signing out');
        await supabase.auth.signOut({ scope: 'global' });
        
        // Clear local storage
        Object.keys(localStorage).forEach((key) => {
          if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
            localStorage.removeItem(key);
          }
        });
        
        // Redirect to login page
        if (window.location.pathname.startsWith('/dashboard')) {
          window.location.href = '/auth';
        }
      } else if (error) {
        // Other errors (including timeouts) - don't logout
        console.warn('Profile check failed but continuing with auth flow:', error.message);
      } else {
        console.log('Profile check successful');
      }
    } catch (profileError) {
      console.error('Error checking user profile:', profileError);
      
      // Don't block the auth flow if profile check fails
      console.log('Continuing with auth flow despite profile check error');
    }
  }
});