name: Minimal Test

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'hello'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test step
      run: echo "Test successful: ${{ inputs.test_input }}"
